### ISSUE TITLE
Investigate usage of partials for embedded templates

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/noddity-render-dom#1]
We investigated partials a while ago and had an issue with them. Maybe the issue was that we didn't know how to change a partial's template?

Now we know about [`ractive.setPartial()`](http://docs.ractivejs.org/latest/ractive-resetpartial)!

Here is a [jsfiddle](http://jsfiddle.net/ddzg0uvw/1/) that utilizes `ractive.setPartial()`, but I'm not sure it proves a thing. While `ractive.setPartial()` seems to work fine, we should probably do more testing.

cc @TehShrike

**Comment by TehShrike** [comment]
The thing I'm worried about having to hack in is updating the data object visible to the partial, and not the rest of the template the partial is embedded in.  If an embedded template's title changes from "Hello" to "Howdy", we need any `{{title}}` references inside the template to reflect the new value, but that shouldn't affect the rest of the document outside that embedded template.

So how to get "local variables" that we can change?

**Comment by ArtskydJ** [comment]
Maybe we can get local variables using [partial context](http://docs.ractivejs.org/latest/partials#partial-context)?

**Comment by TehShrike** [comment]
Yeah, we'll just have to nest them so that we can replace them.

So this would be what would show up in the outer template, wherever the `::someTemplate|propertyOne=20|propertyTwo=30::` text was originally:

```
{{>someTemplateContext}}
```

And then we'd have to set up a `someTemplateContext` partial something like this:

```
{{#partial someTemplateContext}}
  {{>someTemplate { propertyOne: 20, propertyTwo: 30, title: 'Title of the post', date: '2015-09-09 00:00:00 }}}
{{/partial someTemplateContext}}
```

Then whenever the post of the embedded template changes, we have to `resetTemplate` on the `someTemplateContext` to get the updated metadata, and also `resetTemplate`  `someTemplate` to drop in the new template html itself.

**Comment by ArtskydJ** [comment]
I don't understand why we need `someTemplateContext` at all.

Why not just have this...
```
::someTemplate|propOne=20|propTwo=30::
```
...turn into this...
```html
<span class='noddity-template' data-noddity-post-file-name='someTemplate' data-noddity-template-arguments='{"propOne":20,"propTwo":30}'></span>
```
...turn into this?
```html
<span class='noddity-template' data-noddity-post-file-name='someTemplate' data-noddity-template-arguments='{"propOne":20,"propTwo":30}'>
    {{>someTemplate { propOne: 20, propTwo: 30, title: 'Post Title', date: '2015-09-09 00:00:00' }}}
</span>
```

Does it have something to do with making the visual transition smoother, or remembering the metadata?

**Comment by TehShrike** [comment]
Because if `someTemplate`'s title changes from `'Post Title'` to `'Something Cool'`, we don't have any way to update that - we can only reset the template's html, we can't replace the partial in its parent template.

Or at least, that's what I've been assuming - I'd rather not have to mess with resetting the parent's template whenever an embedded template changes.
